name: Releases

on: 
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifact: "res"
        bodyFile: "body.md"
        token: ${{ secrets.GITHUB_TOKEN }}
