name: Releases

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "res"
        token: ${{ secrets.GITHUB_TOKEN }}
